version: '2'
services:
    back:
        build: ./back
        restart: on-failure
        ports:
            - "3000:3000"
            - "4242:4242"
        volumes:
            - ./front:/usr/app/
            - /usr/app/node_modules
        links:
            - "neo4j"
        depends_on:
            - "neo4j"
        environment:
            DB_USR: "neo4j"
            DB_PWD: "42"
            DB_URL: "bolt://neo4j:7687"
            JWT_KEY: "hello world"
        command: ["./wait-for-it.sh", "neo4j:7687","-t", "0", "--", "node", "api.js"]
    front:
        build: ./front
        restart: on-failure
        ports:
            - "80:80"
        links:
            - "back"
        depends_on:
            - "back"
        environment:
            REACT_APP_API_URL: "http://back:3000"
            REACT_APP_SOCKET_URL: "http://back:4242"
    neo4j:
        image: neo4j:latest
        ports:
            - '7474:7474'
            - '7473:7473'
            - '7687:7687'
        environment:
            NEO4J_AUTH: "neo4j/42"